version: "3.8"
services:
  generalisation-agent:
    build:
      context: .
      dockerfile: TestDockerfile.dockerfile
    volumes:
      - ./media/cc/2T/load_model:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]