# Use Alpine Linux as the base image
FROM alpine:3.20.2

# Install Python and psutil
RUN apk add --no-cache python3 py3-pip py3-psutil procps

# Keep the container running
CMD ["tail", "-f", "/dev/null"]