# Use Alpine Linux as the base image
FROM alpine:3.20.2

# Install Python, psutil, du, and free
RUN apk add --no-cache python3 py3-pip py3-psutil procps coreutils util-linux

# Make du and free read-only
RUN chattr +i /usr/bin/du /usr/bin/free

# Keep the container running
CMD ["tail", "-f", "/dev/null"]
