FROM debian

# Install Python, pip, and required utilities
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-psutil \
    procps \
    coreutils \
    && rm -rf /var/lib/apt/lists/* \
    && ln -s $(which python3) /usr/bin/python
