# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY scripts/space_warmer.py .
COPY scripts/space_warmer.sh .

# Make the script executable
RUN chmod +x space_warmer.py
RUN chmod +x space_warmer.sh

# Command to run on container start
CMD ["./space_warmer.sh"]
